### ISSUE TITLE
Introduce permalink to associate a TD / TM example

### ISSUE THREAD

**Issue by sebastiankb** [eclipse/editdor#13]
The JSON-LD playground allows to generate a permalink that associate an example that was created like [here](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22name%22%3A%22ediTDor%22%2C%22description%22%3A%22A%20cool%20WoT%20tool!%22%7D).

It would be cool to have the same feature for the ediTDor. This would help to exchange examples without copying the whole TD / TM somewhere.

**Comment by fexpal** [comment]
I think this is already implemented, am I right?
