### ISSUE TITLE
Add new Link

### ISSUE THREAD

**Issue by sebastiankb** [eclipse/editdor#25]
beside of the "Add new (top level) Form" there should be "Add new "Add new top level Link. There we could apply the new relation types that are currently introduced in the TD: https://github.com/w3c/wot-thing-description/pull/1034

The rendered version can be seen here: https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1034.html#links-relation-types-values

The process should be also part in the assistance when creating a new TD / TM. E.g., it can be asked if a TD instance is an instance of a Thing Model or a Thing Model extends another Thing Model etc.

**Comment by BessemMnif** [comment]
resolved by #49
