### ISSUE TITLE
Pretty print/formatting

### ISSUE THREAD

**Issue by sebastiankb** [eclipse/editdor#27]
Sometimes you will copy a TD to the editor window such as http://plugfest.thingweb.io:8083/smart-coffee-machine

It would be nice if the TD could be formatted in a readable presentation.

**Comment by fexpal** [comment]
That is already possible. 
It can be done by a right click in the left editor part and selecting "Format Document".

**Comment by fexpal** [comment]
Do you think we can close this issue or would you like to see the hotkeys working?

**Comment by sebastiankb** [comment]
thanks, this feature works perfect. Issue can be closed
