### ISSUE TITLE
Sort Properties

### ISSUE THREAD

**Issue by fexpal** [eclipse/editdor#3]
As a User I want to have the possibility to sort the properties in order to get a better overview of all properties.

- [x] First step would be to add a button that can sort them alphabetically.

- [ ] Second step could be to add a Drag and Drop option for the properties.

**Comment by sebastiankb** [comment]
maybe there can be an option based on semantic context such as sensor-based properties, parameter-based properties, etc.

**Comment by fexpal** [comment]
IMO the second step is not necessary at the moment, so I would like to close this issue. @sebastiankb

**Comment by sebastiankb** [comment]
ok from my side
