### ISSUE TITLE
Hyperlink for logo

### ISSUE THREAD

**Issue by egekorkan** [eclipse/editdor#58]
Currently, the logo on the top left is just an image with no hyperlink behind it. It would be nice to point to the website itself so that I can easily open another instance of the website in another tab or window. Now I need to open a new tab and enter the URL.

**Comment by BessemMnif** [comment]
Which logo exactly you are talking about (Web of Things or edit{td}or logo) and what is the corresponding URL you expected to be open ?

**Comment by egekorkan** [comment]
Sorry for not being clear. I mean the editdor logo with the expected URL being https://eclipse.github.io/editdor/
