### ISSUE TITLE
Saved files should use correct file endings and better filenames

### ISSUE THREAD

**Issue by egekorkan** [eclipse/editdor#59]
When clicked on save or save as, the files are prompted to be saved as untitled.txt  . Firstly, TMs should use tm.jsonld and TDs td.jsonld and then for the filename, title or id can be used.

**Comment by egekorkan** [comment]
Also, it would be nice to have a difference between "save" and "save as". If nothing is planned, it would be good to remove one of them to clean up the top bar a bit.

**Comment by BessemMnif** [comment]
> Also, it would be nice to have a difference between "save" and "save as". If nothing is planned, it would be good to remove one of them to clean up the top bar a bit.

"Save" and "save as" are different when using the Chrome browser. "Save as" allows to save the changes to the file directly to your local machine (no window will pop up) and this after using "Save" at least one time. The reason is that Chrome browser supports a filesystem API allows to save changes to the file directly after getting the permission from the user.

**Comment by egekorkan** [comment]
I see the difference now when trying with Chrome (I am a firefox user). I would still have some feedback:
- What should firefox users see: Hiding one of the options?
- On chrome, the behavior of the "Save" indeed works but is a bit _silent_ according to my taste. There is a tiny icon on the URL bar that indicates this but if I click "Save" I see nothing as a user and I have first thought that it is actually not working. It would be nice to have some animation on the "Save" button or display a small notification somewhere saying "saved ✔️"
- On chrome, I am not asked for any permission in the beginning. Is this normal? (Of course, I choose the file location when I click but any subsequent save is allowed without any permission)

**Comment by BessemMnif** [comment]
> * On chrome, I am not asked for any permission in the beginning. Is this normal? (Of course, I choose the file location when I click but any subsequent save is allowed without any permission)

Based on the documentation of File System Access API,  if the permission to write hasn't been granted, the browser will prompt the user for permission. Here I suppose that if you create a new Td and "save it as" you are implicitly giving that permission. On the other side if you open a file from your local machine, modify it and try to "save" it you will be asked for the permission.

**Comment by egekorkan** [comment]
> On the other side if you open a file from your local machine, modify it and try to "save" it you will be asked for the permission.

This is indeed correct (just tested). I guess that if it is a bug, it is for the WHATWG :D
