### ISSUE TITLE
Adding links requires fetchable resources 

### ISSUE THREAD

**Issue by egekorkan** [eclipse/editdor#60]
I wanted to add some dummy TDs/TMs linked to a TD/TM via the links container. The pop-up of the user interface tries to actually fetch the resource even if the resource is located at example.com or localhost. When it cannot find it, it shows an error but it is actually added to the interface and to the editor side. I would need to understand why the fetching functionality is needed but I think that the error message can be extended by saying that the resource could not be fetched but the link is actually added

**Comment by BessemMnif** [comment]
The editdor checks first if the resource is an URL, if this is the case it verifies if the URL leads to a valid Thing Description.
If the link corresponds to a valid Thing Description, then an info button will be added next to the link rectangle and we can see the resulting Thing Description on the same tab using the list above the editor. If not, then the link is added without an info button.
Here we assume that the user can link its TD/TM to an already deployed TD or just to a a web link (that can  represent an image or whatever)
In my opinion we don't need to have an error message so either to consider the link as a TD or just a simple string 
I hope I understood correctly your question

**Comment by egekorkan** [comment]
> The editdor checks first if the resource is an URL, if this is the case it verifies if the URL leads to a valid Thing Description.
If the link corresponds to a valid Thing Description, then an info button will be added next to the link rectangle and we can see the resulting Thing Description on the same tab using the list above the editor. 

This is fine

> If not, then the link is added without an info button.

This also happens but there is an error displayed first that the TD cannot be fetched. However, the link is still added.

> In my opinion we don't need to have an error message so either to consider the link as a TD or just a simple string

There is already an error message and I find it misleading a bit. The link is added regardless of the error message but the error gives the impression that it is not. That is why I have proposed  that the error message can be extended by saying that the resource could not be fetched but the link is actually added
