### ISSUE TITLE
Warning for missing forms in TMs

### ISSUE THREAD

**Issue by egekorkan** [eclipse/editdor#62]
For the TM below which does not have forms in the affordances, there is a warning saying they are missing. This is not following the standard.

https://eclipse.github.io/editdor/?td=%7B%22%40context%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%22%2C%22title%22%3A%22ediTDor%20Thing%22%2C%22%40type%22%3A%22tm%3AThingModel%22%2C%22securityDefinitions%22%3A%7B%22nosec_sc%22%3A%7B%22scheme%22%3A%22nosec%22%7D%7D%2C%22security%22%3A%22nosec_sc%22%2C%22properties%22%3A%7B%22asd%22%3A%7B%22title%22%3A%22asd%22%2C%22observable%22%3Afalse%2C%22readOnly%22%3Afalse%7D%7D%2C%22actions%22%3A%7B%22dsf%22%3A%7B%22title%22%3A%22dsf%22%7D%7D%7D

**Comment by BessemMnif** [comment]
> For the TM below which does not have forms in the affordances, there is a warning saying they are missing. This is not following the standard.
> 
> https://eclipse.github.io/editdor/?td=%7B%22%40context%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%2Fv1%22%2C%22title%22%3A%22ediTDor%20Thing%22%2C%22%40type%22%3A%22tm%3AThingModel%22%2C%22securityDefinitions%22%3A%7B%22nosec_sc%22%3A%7B%22scheme%22%3A%22nosec%22%7D%7D%2C%22security%22%3A%22nosec_sc%22%2C%22properties%22%3A%7B%22asd%22%3A%7B%22title%22%3A%22asd%22%2C%22observable%22%3Afalse%2C%22readOnly%22%3Afalse%7D%7D%2C%22actions%22%3A%7B%22dsf%22%3A%7B%22title%22%3A%22dsf%22%7D%7D%7D

That`s rather true and even if the security field is deleted we get warnings or normally this should not be the case (Thing Model definitions will be also valid if there are no JSON members like forms, base, securityDefinitions, and security)
