### ISSUE TITLE
UX Improvement for Sharing

### ISSUE THREAD

**Issue by egekorkan** [eclipse/editdor#63]
- Minor improvement

Currently, when I click on the Share button, a link for the TD/TM is automatically copied to the clipboard. I think this is mostly fine but then the pop-up window should be improved:
- More visual feedback that it is already copied. (see below for one option)
- The Share button in the pop-up has no real use. I think that a small animation can be played in the beginning saying "Link Copied" instead of "Share"
- Cancel should be replaced with Close since there is no way for the operation to be cancelled.

**Comment by BessemMnif** [comment]
> * I think that a small animation can be played in the beginning saying "Link Copied" 

In the pop-up there is a description saying "A link to this TD was copied to your clipboard." Normally this is sufficient to tell the user that the link is Copied.

**Comment by egekorkan** [comment]
> This is indeed correct, In my opinion this button should be removed

I think once that is done, there would be less need for the small animation proposal since the user would be tempted to read. With the share button, my first intuition is to click the button rather than reading (humans...) :)
