### ISSUE TITLE
@type Thing not being specified generating TDs out of TMs in demo deployment

### ISSUE THREAD

**Issue by Silvanoc** [eclipse/editdor#75]
The [current version of the Thing Description Working Draft](https://www.w3.org/TR/wot-thing-description11) states:

> The tm:ThingModel value of the top-level @type MUST to be replaced by the value Thing in the [Partial TD](https://www.w3.org/TR/wot-thing-description11/#dfn-partial-td) instance.

but the current demo deployment https://eclipse.github.io/editdor/ is not doing so.

I haven't found any code taking care of that replacement, therefore I suppose that it isn't a deployment issue (like in the case of #74), but a missing feature.

**Comment by sebastiankb** [comment]
Thanks for the pointer. Please not the this feature was updated with

> The tm:ThingModel value of the top-level @type MUST be removed in the Partial TD.

Also see [here](https://w3c.github.io/wot-thing-description/#thing-model-td-generation-processor-type). This was one of the last minutes updates and will be valid for the Candidate Recommendation.
