### ISSUE TITLE
Swapping left and right windows

### ISSUE THREAD

**Issue by egekorkan** [eclipse/editdor#83]
In a chat with @danielpeintner, @sebastiankb, and @wiresio , we discussed the possibility of swapping the place of the left and right windows since the current right-hand side is mainly used to create a TD. However, the intuition of some users might be to start from left.

In swagger editor or even latex editors, the output is on the right but those are really just the output. However, editdor excels at the creation of TDs and thus the workflow would make more sense in putting the interactable UI on the left side, making the TD a mere output. Given that this might be a change that some actually do not want, it would be nice to let users swap the place the order.

**Comment by fexpal** [comment]
I do like the idea a lot. 
Created a PR for this, so we can try it: 
https://github.com/eclipse/editdor/pull/84
