### ISSUE TITLE
Error reported on newly created TM

### ISSUE THREAD

**Issue by Silvanoc** [eclipse/editdor#87]
Asking for a New TM the resulting skeleton is being reported to be erroneous, though it looks good to me. The error message is also really weird "[...] should NOT be valid [...]" 🤨

Issue observed on currently deployed version 0.5.0.

How to reproduce it? Simply click on "New" and select "ThingModel" as type in the dialog without entering any other data.

See screenshot:

![image](https://user-images.githubusercontent.com/8374400/224067279-ecb07935-95c7-4f5b-9a6a-c423c49cbe43.png)

**Comment by egekorkan** [comment]
I think that it's thinking that it's a TD since the td schema prohibits tm:ThingModel in `@type`

**Comment by spf00** [comment]
The problem is actually that currently all inputs are treated as TDs as the only validation function that is called is "tdValidator(...)". We have to differentiate between TD and TM and call the according "tdValidator" or "tmValidator" functions.

**Comment by Silvanoc** [comment]
I've just deployed version 0.6.0 and can confirm that it works now.
